language: php
matrix:
    include:
        - php: 7.1
          env: deps=high
        - php: 7.1
          env: deps=low
        - php: 7.2
          env: deps=low
        - php: 7.2
          env: deps=high
    fast_finish: true

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    TYPO3_PATH_WEB=$TRAVIS_BUILD_DIR/.Build/Web
    typo3DatabaseName=lock
    typo3DatabaseHost=localhost
    typo3DatabaseUsername=root
    typo3DatabasePassword=''
    typo3RedisHost=localhost
    typo3RedisDatabase=1

services:
  - redis-server
  - mysql

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; else composer update; fi;

script:
  - .Build/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover